// fiberpath_gui/src/components/editors/HelicalLayerEditor.svelte
<script lang="ts">
  import { projectSession } from "../../state/project-session.svelte";
  import { parseNumericInput } from "../../lib/numericFields";
  import { debounce } from "../../lib/debounce";
  import {
    validateHelicalField,
    getHelicalGeometryHint,
    type HelicalNumericField,
  } from "../../lib/helicalValidation";
  import type { HelicalLayer } from "../../types/project";
  import type { UiValidationField } from "../../lib/validationErrors";
  import NumberField from "../../ui/NumberField.svelte";

  let { layerId }: { layerId: string } = $props();

  interface FieldConfig {
    field: HelicalNumericField;
    label: string;
    tooltip: string;
    unit?: string;
    step?: string;
  }

  const CONFIGS: FieldConfig[] = [
    { field: "wind_angle", label: "Wind Angle", unit: "°", step: "0.1",
      tooltip: "Angle between fiber path and mandrel axis: 0 degrees is axial, 90 degrees is hoop. Helical layers must be > 0 and <= 90." },
    { field: "pattern_number", label: "Pattern Number", step: "1",
      tooltip: "How many helical bands the layer is split into around the circumference. Must be a positive integer and must divide the computed circuit count." },
    { field: "skip_index", label: "Skip Index", step: "1",
      tooltip: "Stride used to move between helical bands each circuit. Must be a positive integer and coprime with pattern number to visit every band." },
    { field: "lock_degrees", label: "Lock Degrees", unit: "°", step: "0.1",
      tooltip: "Extra mandrel rotation at the lock point for stable termination/restart alignment between circuits." },
    { field: "lead_in_mm", label: "Lead-in", unit: "mm", step: "0.1",
      tooltip: "Linear approach distance before the main winding path starts; used to smooth fiber entry onto the part." },
    { field: "lead_out_degrees", label: "Lead-out Degrees", unit: "°", step: "0.1",
      tooltip: "Extra mandrel rotation after the main path ends; used to smooth exit and maintain placement continuity." },
  ];

  const FIELD_MAP: Record<HelicalNumericField, UiValidationField> = {
    wind_angle: "layers.helical.wind_angle",
    pattern_number: "layers.helical.pattern_number",
    skip_index: "layers.helical.skip_index",
    lock_degrees: "layers.helical.lock_degrees",
    lead_in_mm: "layers.helical.lead_in_mm",
    lead_out_degrees: "layers.helical.lead_out_degrees",
  };

  const layer = $derived(projectSession.document.layers.find((l) => l.id === layerId));
  const helical = $derived(layer?.type === "helical" ? layer.helical : undefined);
  const backend = $derived(projectSession.validationErrors);

  let errors = $state<Partial<Record<HelicalNumericField, string>>>({});

  const validateAll = (h: HelicalLayer) => {
    const next: Partial<Record<HelicalNumericField, string>> = {};
    for (const c of CONFIGS) {
      const e = validateHelicalField(c.field, h[c.field], h);
      if (e) next[c.field] = e;
    }
    errors = next;
  };
  const debouncedValidateAll = debounce((h: HelicalLayer) => validateAll(h));

  // Validate on mount and whenever the helical values change (mirrors the React
  // editor's debounced effect on the store value), so re-selecting a layer that
  // already holds invalid values surfaces its errors without needing a keystroke.
  $effect(() => {
    if (helical) {
      debouncedValidateAll(helical);
    } else {
      errors = {};
    }
  });

  const isInteger = (field: HelicalNumericField) =>
    field === "pattern_number" || field === "skip_index";

  function onInput(field: HelicalNumericField, raw: string) {
    const h = helical;
    if (!h) return;
    const value = parseNumericInput(raw, isInteger(field));
    projectSession.setValidationError(FIELD_MAP[field], undefined);
    // pattern/skip share a coprimality rule — clear both so a fixed pair re-checks.
    if (isInteger(field)) {
      projectSession.setValidationError("layers.helical.pattern_number", undefined);
      projectSession.setValidationError("layers.helical.skip_index", undefined);
    }
    const nextHelical = { ...h, [field]: value };
    projectSession.updateLayer(layerId, { helical: nextHelical });
    // The $effect above re-validates from the updated store value.
  }

  function onBlur(field: HelicalNumericField, raw: string) {
    const h = helical;
    if (!h) return;
    const value = parseNumericInput(raw, isInteger(field));
    errors = { ...errors, [field]: validateHelicalField(field, value, h) };
  }

  function setSkipNearLock(checked: boolean) {
    const h = helical;
    if (!h) return;
    projectSession.updateLayer(layerId, { helical: { ...h, skip_initial_near_lock: checked } });
  }

  const geometryHint = $derived(
    helical
      ? getHelicalGeometryHint(
          helical,
          projectSession.document.mandrel.diameter,
          projectSession.document.tow.width,
        )
      : undefined,
  );
</script>

{#if helical}
  <div class="editor">
    {#each CONFIGS as config (config.field)}
      <NumberField
        id={`${config.field}-${layerId}`}
        label={config.label}
        tooltip={config.tooltip}
        unit={config.unit}
        step={config.step}
        value={helical[config.field]}
        error={errors[config.field] ?? backend[FIELD_MAP[config.field]]}
        oninput={(raw) => onInput(config.field, raw)}
        onblur={(raw) => onBlur(config.field, raw)}
      />
    {/each}

    {#if geometryHint}
      <p class="editor__hint editor__hint--warning">{geometryHint}</p>
    {/if}

    <label class="editor__check">
      <input
        type="checkbox"
        checked={helical.skip_initial_near_lock}
        onchange={(e) => setSkipNearLock(e.currentTarget.checked)}
      />
      <span>Skip Initial Near Lock</span>
    </label>
    <p class="editor__hint">
      Skip the first near-lock handling step. Enable only when you intentionally
      want custom lock behavior.
    </p>
  </div>
{/if}

<style>
  .editor__check {
    display: flex;
    align-items: center;
    gap: var(--spacing-sm);
    margin-top: var(--spacing-sm);
    font-size: var(--font-size-base);
    cursor: pointer;
  }
  .editor__hint {
    margin: var(--spacing-sm) 0 0;
    font-size: var(--font-size-xs);
    color: var(--color-text-muted);
    line-height: var(--line-height-normal);
  }
  .editor__hint--warning {
    color: var(--color-warning);
  }
</style>

// fiberpath_gui/src/components/editors/HelicalLayerEditor.tsx
import { useEffect, useState } from "react";
import { useDebouncedValue } from "../../hooks/useDebouncedValue";
import { useProjectStore } from "../../stores/projectStore";
import type { LayerEditorBaseProps } from "../../types/components";
import type { HelicalLayer } from "../../types/project";
import {
  validateHelicalField,
  getHelicalGeometryHint,
  type HelicalNumericField,
} from "../../lib/helicalValidation";
import { setFieldError } from "../../lib/numericFields";
import type { UiValidationField } from "../../lib/validationErrors";
import { LayerNumericField } from "./LayerNumericField";

interface HelicalLayerEditorProps extends LayerEditorBaseProps {
  // HelicalLayerEditor uses only the base props
}

interface HelicalFieldConfig {
  field: HelicalNumericField;
  label: string;
  tooltip: string;
  unit?: string;
  step?: string;
  integer?: boolean;
}

const HELICAL_FIELD_CONFIGS: HelicalFieldConfig[] = [
  {
    field: "wind_angle",
    label: "Wind Angle",
    tooltip:
      "Angle between fiber path and mandrel axis: 0 degrees is axial, 90 degrees is hoop. Helical layers must be > 0 and <= 90.",
    unit: "°",
    step: "0.1",
  },
  {
    field: "pattern_number",
    label: "Pattern Number",
    tooltip:
      "How many helical bands the layer is split into around the circumference. Must be a positive integer and must divide the computed circuit count.",
    integer: true,
    step: "1",
  },
  {
    field: "skip_index",
    label: "Skip Index",
    tooltip:
      "Stride used to move between helical bands each circuit. Must be a positive integer and coprime with pattern number to visit every band.",
    integer: true,
    step: "1",
  },
  {
    field: "lock_degrees",
    label: "Lock Degrees",
    tooltip:
      "Extra mandrel rotation at the lock point for stable termination/restart alignment between circuits.",
    unit: "°",
    step: "0.1",
  },
  {
    field: "lead_in_mm",
    label: "Lead-in",
    tooltip:
      "Linear approach distance before the main winding path starts; used to smooth fiber entry onto the part.",
    unit: "mm",
    step: "0.1",
  },
  {
    field: "lead_out_degrees",
    label: "Lead-out Degrees",
    tooltip:
      "Extra mandrel rotation after the main path ends; used to smooth exit and maintain placement continuity.",
    unit: "°",
    step: "0.1",
  },
];

const HELICAL_VALIDATION_FIELD_MAP: Record<HelicalNumericField, UiValidationField> = {
  wind_angle: "layers.helical.wind_angle",
  pattern_number: "layers.helical.pattern_number",
  skip_index: "layers.helical.skip_index",
  lock_degrees: "layers.helical.lock_degrees",
  lead_in_mm: "layers.helical.lead_in_mm",
  lead_out_degrees: "layers.helical.lead_out_degrees",
};

const DEFAULT_HELICAL: HelicalLayer = {
  wind_angle: 45,
  pattern_number: 3,
  skip_index: 2,
  lock_degrees: 5,
  lead_in_mm: 10,
  lead_out_degrees: 5,
  skip_initial_near_lock: false,
};

export function HelicalLayerEditor({ layerId }: HelicalLayerEditorProps) {
  const layers = useProjectStore((state) => state.project.layers);
  const mandrelDiameter = useProjectStore((state) => state.project.mandrel.diameter);
  const towWidth = useProjectStore((state) => state.project.tow.width);
  const validationErrors = useProjectStore((state) => state.validationErrors);
  const updateLayer = useProjectStore((state) => state.updateLayer);
  const setValidationError = useProjectStore((state) => state.setValidationError);
  const [errors, setErrors] = useState<Partial<Record<HelicalNumericField, string>>>({});

  const layer = layers.find((item) => item.id === layerId);
  const helical =
    layer && layer.type === "helical" && layer.helical ? layer.helical : null;
  const debouncedHelical = useDebouncedValue(helical ?? DEFAULT_HELICAL, 300);

  useEffect(() => {
    if (!helical) {
      setErrors({});
      return;
    }

    const nextErrors: Partial<Record<HelicalNumericField, string>> = {};

    for (const config of HELICAL_FIELD_CONFIGS) {
      const error = validateHelicalField(
        config.field,
        debouncedHelical[config.field],
        debouncedHelical,
      );
      if (error) {
        nextErrors[config.field] = error;
      }
    }

    setErrors(nextErrors);
  }, [debouncedHelical, helical]);

  if (!layer || layer.type !== "helical" || !helical) {
    return null;
  }

  const handleNumericChange = (field: HelicalNumericField, value: number) => {
    const currentHelical = helical || DEFAULT_HELICAL;
    setValidationError(HELICAL_VALIDATION_FIELD_MAP[field], undefined);
    if (field === "pattern_number" || field === "skip_index") {
      setValidationError("layers.helical.pattern_number", undefined);
      setValidationError("layers.helical.skip_index", undefined);
    }

    updateLayer(layerId, {
      helical: {
        ...currentHelical,
        [field]: value,
      },
    });
  };

  const handleNumericBlur = (field: HelicalNumericField, value: number) => {
    const error = validateHelicalField(field, value, helical);
    setFieldError(setErrors, field, error);
  };

  const handleSkipNearLockChange = (checked: boolean) => {
    const currentHelical = helical || DEFAULT_HELICAL;

    updateLayer(layerId, {
      helical: {
        ...currentHelical,
        skip_initial_near_lock: checked,
      },
    });
  };

  const geometryHint = getHelicalGeometryHint(helical, mandrelDiameter, towWidth);

  return (
    <div className="layer-editor">
      <h3 className="layer-editor__title">Helical Layer Properties</h3>

      {HELICAL_FIELD_CONFIGS.map((config) => {
        const backendError =
          validationErrors[HELICAL_VALIDATION_FIELD_MAP[config.field]];
        return (
          <LayerNumericField
            key={config.field}
            id={`${config.field}-${layerId}`}
            label={config.label}
            tooltip={config.tooltip}
            value={helical[config.field]}
            step={config.step}
            unit={config.unit}
            integer={config.integer}
            error={errors[config.field] || backendError}
            onChange={(value) => handleNumericChange(config.field, value)}
            onBlur={(value) => handleNumericBlur(config.field, value)}
          />
        );
      })}

      {geometryHint && (
        <p className="layer-editor__hint layer-editor__hint--warning">
          {geometryHint}
        </p>
      )}

      <div className="layer-editor__group">
        <label className="layer-editor__checkbox-label">
          <input
            type="checkbox"
            checked={helical.skip_initial_near_lock}
            onChange={(e) => handleSkipNearLockChange(e.target.checked)}
            className="layer-editor__checkbox"
          />
          <span className="layer-editor__checkbox-text">
            Skip Initial Near Lock
          </span>
        </label>
        <p className="layer-editor__hint">
          Skip the first near-lock handling step. Enable only when you
          intentionally want custom lock behavior.
        </p>
      </div>
    </div>
  );
}
