// fiberpath_gui/src/components/forms/MachineSettingsForm.svelte
<script lang="ts">
  import { projectSession } from "../../state/project-session.svelte";
  import { parseNumericInput } from "../../lib/numericFields";
  import { debounce } from "../../lib/debounce";
  import NumberField from "../../ui/NumberField.svelte";

  // Feed-rate validation is bespoke (not a NUMERIC_RANGES entry) — keep the exact
  // messages the React form used for behaviour parity.
  const validate = (value: number): string | undefined => {
    if (Number.isNaN(value) || value <= 0) {
      return "Feed rate must be greater than 0";
    }
    if (value > 10000) {
      return "Feed rate seems unreasonably high";
    }
    return undefined;
  };

  // minimal: see MandrelForm — live validation fires on input/blur only;
  // programmatic-document-change validation lands with the load path (#217).
  let error = $state<string | undefined>(undefined);

  const debouncedValidate = debounce((v: number) => (error = validate(v)));

  function onInput(raw: string) {
    const value = parseNumericInput(raw);
    projectSession.setValidationError("machine.defaultFeedRate", undefined);
    projectSession.updateDefaultFeedRate(value);
    debouncedValidate(value);
  }

  function onBlur(raw: string) {
    error = validate(parseNumericInput(raw));
  }

  const feedRate = $derived(projectSession.document.defaultFeedRate);
  const backend = $derived(projectSession.validationErrors);
</script>

<div class="param-form">
  <h3 class="param-form__title">Machine Settings</h3>

  <NumberField
    id="defaultFeedRate"
    label="Default Feed Rate"
    unit="mm/min"
    step="100"
    min="1"
    max="10000"
    value={feedRate}
    error={error ?? backend["machine.defaultFeedRate"]}
    oninput={onInput}
    onblur={onBlur}
  />
</div>

// fiberpath_gui/src/components/forms/MachineSettingsForm.tsx
import { useEffect, useState } from "react";
import { useDebouncedValue } from "../../hooks/useDebouncedValue";
import { useProjectStore } from "../../stores/projectStore";
import { parseNumericInput, setFieldError } from "../../lib/numericFields";

type MachineSettingsField = "defaultFeedRate";

const validateFeedRate = (value: number): string | undefined => {
  if (Number.isNaN(value) || value <= 0) {
    return "Feed rate must be greater than 0";
  }
  if (value > 10000) {
    return "Feed rate seems unreasonably high";
  }
  return undefined;
};

export function MachineSettingsForm() {
  const defaultFeedRate = useProjectStore(
    (state) => state.project.defaultFeedRate,
  );
  const updateDefaultFeedRate = useProjectStore(
    (state) => state.updateDefaultFeedRate,
  );
  const setValidationError = useProjectStore((state) => state.setValidationError);
  const backendFeedRateError = useProjectStore(
    (state) => state.validationErrors["machine.defaultFeedRate"],
  );

  const [errors, setErrors] = useState<
    Partial<Record<MachineSettingsField, string>>
  >({});
  const debouncedFeedRate = useDebouncedValue(defaultFeedRate, 300);

  useEffect(() => {
    setFieldError(
      setErrors,
      "defaultFeedRate",
      validateFeedRate(debouncedFeedRate),
    );
  }, [debouncedFeedRate]);

  const handleFeedRateChange = (rawValue: string) => {
    setValidationError("machine.defaultFeedRate", undefined);
    updateDefaultFeedRate(parseNumericInput(rawValue));
  };

  const handleFeedRateBlur = (rawValue: string) => {
    const value = parseNumericInput(rawValue);
    setFieldError(setErrors, "defaultFeedRate", validateFeedRate(value));
  };

  return (
    <div className="param-form">
      <h3 className="param-form__title">Machine Settings</h3>

      <div className="param-form__group">
        <label htmlFor="defaultFeedRate" className="param-form__label">
          Default Feed Rate
        </label>
        <div className="param-form__input-wrapper">
          <input
            id="defaultFeedRate"
            type="number"
            value={defaultFeedRate}
            onChange={(e) => handleFeedRateChange(e.target.value)}
            onBlur={(e) => handleFeedRateBlur(e.target.value)}
            min="1"
            max="10000"
            step="100"
            className={`param-form__input ${errors.defaultFeedRate || backendFeedRateError ? "param-form__input--error" : ""}`}
          />
          <span className="param-form__unit">mm/min</span>
        </div>
        {(errors.defaultFeedRate || backendFeedRateError) && (
          <span className="param-form__error">
            {errors.defaultFeedRate || backendFeedRateError}
          </span>
        )}
      </div>
    </div>
  );
}
