// fiberpath_gui/src/components/forms/TowForm.tsx
import { useState } from "react";
import { useProjectStore } from "../../stores/projectStore";
import { NUMERIC_RANGES, validateNumericRange } from "../../types/components";
import { parseNumericInput, setFieldError } from "../../lib/numericFields";

type TowField = "width" | "thickness";

export function TowForm() {
  const tow = useProjectStore((state) => state.project.tow);
  const updateTow = useProjectStore((state) => state.updateTow);

  const [errors, setErrors] = useState<Partial<Record<TowField, string>>>({});

  const handleNumericChange = (field: TowField, rawValue: string) => {
    updateTow({
      [field]: parseNumericInput(rawValue),
    });
  };

  const handleNumericBlur = (field: TowField, rawValue: string) => {
    const value = parseNumericInput(rawValue);
    const error =
      field === "width"
        ? validateNumericRange(value, NUMERIC_RANGES.TOW_WIDTH, "Width")
        : validateNumericRange(value, NUMERIC_RANGES.TOW_THICKNESS, "Thickness");

    setFieldError(setErrors, field, error);
  };

  return (
    <div className="param-form">
      <h3 className="param-form__title">Tow Parameters</h3>

      <div className="param-form__group">
        <label htmlFor="tow-width" className="param-form__label">
          Width
        </label>
        <div className="param-form__input-wrapper">
          <input
            id="tow-width"
            type="number"
            step="0.1"
            min="0"
            value={tow.width}
            onChange={(e) => handleNumericChange("width", e.target.value)}
            onBlur={(e) => handleNumericBlur("width", e.target.value)}
            className={`param-form__input ${errors.width ? "param-form__input--error" : ""}`}
          />
          <span className="param-form__unit">mm</span>
        </div>
        {errors.width && <span className="param-form__error">{errors.width}</span>}
      </div>

      <div className="param-form__group">
        <label htmlFor="tow-thickness" className="param-form__label">
          Thickness
        </label>
        <div className="param-form__input-wrapper">
          <input
            id="tow-thickness"
            type="number"
            step="0.01"
            min="0"
            value={tow.thickness}
            onChange={(e) => handleNumericChange("thickness", e.target.value)}
            onBlur={(e) => handleNumericBlur("thickness", e.target.value)}
            className={`param-form__input ${errors.thickness ? "param-form__input--error" : ""}`}
          />
          <span className="param-form__unit">mm</span>
        </div>
        {errors.thickness && (
          <span className="param-form__error">{errors.thickness}</span>
        )}
      </div>
    </div>
  );
}

// fiberpath_gui/src/components/forms/TowForm.svelte
<script lang="ts">
  import { projectSession } from "../../state/project-session.svelte";
  import { NUMERIC_RANGES, validateNumericRange } from "../../types/components";
  import { parseNumericInput } from "../../lib/numericFields";
  import { debounce } from "../../lib/debounce";
  import NumberField from "../../ui/NumberField.svelte";

  type Field = "width" | "thickness";

  const validate = (field: Field, value: number): string | undefined =>
    field === "width"
      ? validateNumericRange(value, NUMERIC_RANGES.TOW_WIDTH, "Width")
      : validateNumericRange(value, NUMERIC_RANGES.TOW_THICKNESS, "Thickness");

  // minimal: see MandrelForm — live validation fires on input/blur only;
  // programmatic-document-change validation lands with the load path (#217).
  let errors = $state<Partial<Record<Field, string>>>({});

  const debouncedValidate: Record<Field, (v: number) => void> = {
    width: debounce((v: number) => (errors = { ...errors, width: validate("width", v) })),
    thickness: debounce((v: number) => (errors = { ...errors, thickness: validate("thickness", v) })),
  };

  function onInput(field: Field, raw: string) {
    const value = parseNumericInput(raw);
    projectSession.setValidationError(
      field === "width" ? "tow.width" : "tow.thickness",
      undefined,
    );
    projectSession.updateTow({ [field]: value });
    debouncedValidate[field](value);
  }

  function onBlur(field: Field, raw: string) {
    errors = { ...errors, [field]: validate(field, parseNumericInput(raw)) };
  }

  const tow = $derived(projectSession.document.tow);
  const backend = $derived(projectSession.validationErrors);
</script>

<div class="param-form">
  <h3 class="param-form__title">Tow Parameters</h3>

  <NumberField
    id="tow-width"
    label="Width"
    unit="mm"
    step="0.1"
    min="0"
    value={tow.width}
    error={errors.width ?? backend["tow.width"]}
    oninput={(raw) => onInput("width", raw)}
    onblur={(raw) => onBlur("width", raw)}
  />

  <NumberField
    id="tow-thickness"
    label="Thickness"
    unit="mm"
    step="0.01"
    min="0"
    value={tow.thickness}
    error={errors.thickness ?? backend["tow.thickness"]}
    oninput={(raw) => onInput("thickness", raw)}
    onblur={(raw) => onBlur("thickness", raw)}
  />
</div>
