// fiberpath_gui/src/components/dialogs/AboutDialog.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { getVersion } from "@tauri-apps/api/app";
  import { open as openExternal } from "@tauri-apps/plugin-shell";
  import Dialog from "../../ui/Dialog.svelte";

  let { onclose }: { onclose: () => void } = $props();

  let version = $state("…");
  onMount(() => {
    getVersion()
      .then((v) => (version = v))
      .catch(() => (version = "—"));
  });

  const link = (url: string) => () => void openExternal(url).catch(() => {});
</script>

<Dialog title="About FiberPath" {onclose} contentClass="dialog-content--small">
  <div class="about-section">
    <div class="about-logo">
      <div class="about-icon">🧵</div>
      <div class="about-title">
        <h3>FiberPath</h3>
        <p class="about-version">Version {version}</p>
      </div>
    </div>
  </div>

  <div class="about-section">
    <p class="about-description">
      Filament winding path planning and G-code generation for composite manufacturing.
      Create optimized winding patterns for cylindrical mandrels with helical, hoop and
      skip layers.
    </p>
  </div>

  <div class="about-section">
    <h4>Links</h4>
    <div class="about-links">
      <button class="link-button" onclick={link("https://fiberpath.org/fiberpath")}>📚 Documentation</button>
      <button class="link-button" onclick={link("https://github.com/fiberpath/fiberpath")}>💻 GitHub Repository</button>
    </div>
  </div>

  <div class="about-section about-footer">
    <p class="about-copyright">© 2026 Cameron Brooks</p>
    <p class="about-license">Open source software licensed under AGPL v3.</p>
  </div>
</Dialog>

// fiberpath_gui/src/components/dialogs/AboutDialog.tsx
import { open as openExternal } from "@tauri-apps/plugin-shell";
import { getVersion } from "@tauri-apps/api/app";
import { useEffect, useState } from "react";
import type { DialogBaseProps } from "../../types/components";
import { BaseDialog } from "./BaseDialog";
import "../../styles/dialogs.css";

interface AboutDialogProps extends DialogBaseProps {
  isOpen: boolean;
}

export function AboutDialog({ isOpen, onClose }: AboutDialogProps) {
  const [version, setVersion] = useState<string>("Loading...");

  useEffect(() => {
    void getVersion().then(setVersion);
  }, []);

  const handleDocsLink = () => {
    void openExternal("https://fiberpath.org/fiberpath");
  };

  const handleGitHubLink = () => {
    void openExternal("https://github.com/fiberpath/fiberpath");
  };

  return (
    <BaseDialog
      isOpen={isOpen}
      title="About FiberPath"
      onClose={onClose}
      contentClassName="dialog-content--small"
    >
      <div className="about-section">
        <div className="about-logo">
          <div className="about-icon">🧵</div>
          <div className="about-title">
            <h3>FiberPath</h3>
            <p className="about-version">Version {version}</p>
          </div>
        </div>
      </div>

      <div className="about-section">
        <p className="about-description">
          Professional filament winding path planning and G-code generation
          software for composite manufacturing. Create optimized winding
          patterns for cylindrical mandrels with helical, hoop, and skip
          layers.
        </p>
      </div>

      <div className="about-section">
        <h4>Features</h4>
        <ul className="about-features">
          <li>Visual layer authoring with live preview</li>
          <li>JSON Schema validation</li>
          <li>XAB rotational-axis G-code output</li>
          <li>Real-time G-code generation</li>
        </ul>
      </div>

      <div className="about-section">
        <h4>Links</h4>
        <div className="about-links">
          <button className="link-button" onClick={handleDocsLink}>
            📚 Documentation
          </button>
          <button className="link-button" onClick={handleGitHubLink}>
            💻 GitHub Repository
          </button>
        </div>
      </div>

      <div className="about-section about-footer">
        <p className="about-copyright">© 2026 Cameron Brooks</p>
        <p className="about-license">Open source software licensed under AGPL v3.</p>
      </div>
    </BaseDialog>
  );
}
