// fiberpath_gui/src/components/dialogs/DiagnosticsDialog.tsx
import { useEffect, useState } from "react";
import { getRecentFiles } from "../../lib/recentFiles";
import { useProjectStore } from "../../stores/projectStore";
import { useCliHealthContext } from "../../contexts/CliHealthContext";
import type { DialogBaseProps } from "../../types/components";
import { BaseDialog } from "./BaseDialog";
import "../../styles/dialogs.css";

interface DiagnosticsDialogProps extends DialogBaseProps {
  isOpen: boolean;
}

interface DiagnosticsData {
  recentFilesCount: number;
  projectStats: {
    layers: number;
    filePath: string | null;
    isDirty: boolean;
  };
}

export function DiagnosticsDialog({ isOpen, onClose }: DiagnosticsDialogProps) {
  const project = useProjectStore((state) => state.project);
  const {
    version: cliVersion,
    isHealthy: cliHealthy,
    errorMessage,
    lastChecked,
    refresh,
  } = useCliHealthContext();

  const [diagnostics, setDiagnostics] = useState<DiagnosticsData>({
    recentFilesCount: 0,
    projectStats: {
      layers: 0,
      filePath: null,
      isDirty: false,
    },
  });

  useEffect(() => {
    if (!isOpen) {
      return;
    }

    const recentFiles = getRecentFiles();
    setDiagnostics({
      recentFilesCount: recentFiles.length,
      projectStats: {
        layers: project.layers.length,
        filePath: project.filePath,
        isDirty: project.isDirty,
      },
    });

    refresh();
  }, [isOpen, project, refresh]);

  return (
    <BaseDialog
      isOpen={isOpen}
      title="Diagnostics"
      onClose={onClose}
      footer={
        <button className="btn btn--secondary" onClick={onClose}>
          Close
        </button>
      }
    >
      <div className="diagnostics-section">
        <h3>CLI Status</h3>
        <div className="diagnostics-grid">
          <div className="diagnostics-item">
            <span className="diagnostics-label">Health:</span>
            <span
              className={`diagnostics-value ${cliHealthy ? "status-healthy" : "status-error"}`}
            >
              {cliHealthy ? "✓ Healthy" : "✗ Unavailable"}
            </span>
          </div>
          <div className="diagnostics-item">
            <span className="diagnostics-label">Version:</span>
            <span className="diagnostics-value">{cliVersion || "Unknown"}</span>
          </div>
          {!cliHealthy && errorMessage && (
            <div className="diagnostics-item diagnostics-item--full-width">
              <span className="diagnostics-label">Error:</span>
              <span className="diagnostics-value diagnostics-value--error">
                {errorMessage}
              </span>
            </div>
          )}
          {lastChecked && (
            <div className="diagnostics-item">
              <span className="diagnostics-label">Last Checked:</span>
              <span className="diagnostics-value">
                {lastChecked.toLocaleTimeString()}
              </span>
            </div>
          )}
        </div>
        <button className="btn btn--secondary diagnostics-refresh-btn" onClick={refresh}>
          Refresh CLI Status
        </button>
      </div>

      <div className="diagnostics-section">
        <h3>Project Status</h3>
        <div className="diagnostics-grid">
          <div className="diagnostics-item">
            <span className="diagnostics-label">File Path:</span>
            <span className="diagnostics-value diagnostics-value--path">
              {diagnostics.projectStats.filePath || "Untitled"}
            </span>
          </div>
          <div className="diagnostics-item">
            <span className="diagnostics-label">Layer Count:</span>
            <span className="diagnostics-value">{diagnostics.projectStats.layers}</span>
          </div>
          <div className="diagnostics-item">
            <span className="diagnostics-label">Unsaved Changes:</span>
            <span
              className={`diagnostics-value ${diagnostics.projectStats.isDirty ? "status-warning" : "status-healthy"}`}
            >
              {diagnostics.projectStats.isDirty ? "⚠ Yes" : "✓ No"}
            </span>
          </div>
        </div>
      </div>

      <div className="diagnostics-section">
        <h3>Application Data</h3>
        <div className="diagnostics-grid">
          <div className="diagnostics-item">
            <span className="diagnostics-label">Recent Files:</span>
            <span className="diagnostics-value">{diagnostics.recentFilesCount} / 10</span>
          </div>
          <div className="diagnostics-item">
            <span className="diagnostics-label">Temp Files:</span>
            <span className="diagnostics-value">Cleaned on exit</span>
          </div>
        </div>
      </div>

      <div className="diagnostics-section">
        <h3>System Information</h3>
        <div className="diagnostics-grid">
          <div className="diagnostics-item">
            <span className="diagnostics-label">Platform:</span>
            <span className="diagnostics-value">{navigator.platform}</span>
          </div>
          <div className="diagnostics-item">
            <span className="diagnostics-label">User Agent:</span>
            <span className="diagnostics-value diagnostics-value--path">
              {navigator.userAgent}
            </span>
          </div>
        </div>
      </div>
    </BaseDialog>
  );
}

// fiberpath_gui/src/components/dialogs/DiagnosticsDialog.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import Dialog from "../../ui/Dialog.svelte";
  import { cliHealth } from "../../state/cli-health.svelte";
  import { projectSession } from "../../state/project-session.svelte";
  import { getRecentFiles } from "../../lib/recentFiles";

  let { onclose }: { onclose: () => void } = $props();

  const recentCount = getRecentFiles().length;
  const doc = $derived(projectSession.document);

  onMount(() => void cliHealth.refresh());
</script>

<Dialog title="Diagnostics" {onclose}>
  {#snippet footer()}
    <button class="btn btn--secondary" onclick={onclose}>Close</button>
  {/snippet}

  <div class="diagnostics-section">
    <h3>CLI Status</h3>
    <div class="diagnostics-grid">
      <div class="diagnostics-item">
        <span class="diagnostics-label">Health:</span>
        <span class="diagnostics-value" class:status-healthy={cliHealth.isHealthy} class:status-error={!cliHealth.isHealthy}>
          {cliHealth.isHealthy ? "✓ Healthy" : "✗ Unavailable"}
        </span>
      </div>
      <div class="diagnostics-item">
        <span class="diagnostics-label">Version:</span>
        <span class="diagnostics-value">{cliHealth.version || "Unknown"}</span>
      </div>
      {#if !cliHealth.isHealthy && cliHealth.errorMessage}
        <div class="diagnostics-item diagnostics-item--full-width">
          <span class="diagnostics-label">Error:</span>
          <span class="diagnostics-value diagnostics-value--error">{cliHealth.errorMessage}</span>
        </div>
      {/if}
      {#if cliHealth.lastChecked}
        <div class="diagnostics-item">
          <span class="diagnostics-label">Last Checked:</span>
          <span class="diagnostics-value">{cliHealth.lastChecked.toLocaleTimeString()}</span>
        </div>
      {/if}
    </div>
    <button class="btn btn--secondary diagnostics-refresh-btn" onclick={() => cliHealth.refresh()}>
      Refresh CLI Status
    </button>
  </div>

  <div class="diagnostics-section">
    <h3>Project Status</h3>
    <div class="diagnostics-grid">
      <div class="diagnostics-item">
        <span class="diagnostics-label">File Path:</span>
        <span class="diagnostics-value diagnostics-value--path">{projectSession.filePath || "Untitled"}</span>
      </div>
      <div class="diagnostics-item">
        <span class="diagnostics-label">Layer Count:</span>
        <span class="diagnostics-value">{doc.layers.length}</span>
      </div>
      <div class="diagnostics-item">
        <span class="diagnostics-label">Unsaved Changes:</span>
        <span class="diagnostics-value" class:status-warning={projectSession.isDirty} class:status-healthy={!projectSession.isDirty}>
          {projectSession.isDirty ? "⚠ Yes" : "✓ No"}
        </span>
      </div>
    </div>
  </div>

  <div class="diagnostics-section">
    <h3>Application Data</h3>
    <div class="diagnostics-grid">
      <div class="diagnostics-item">
        <span class="diagnostics-label">Recent Files:</span>
        <span class="diagnostics-value">{recentCount} / 10</span>
      </div>
      <div class="diagnostics-item">
        <span class="diagnostics-label">Temp Files:</span>
        <span class="diagnostics-value">Cleaned on exit</span>
      </div>
    </div>
  </div>

  <div class="diagnostics-section">
    <h3>System Information</h3>
    <div class="diagnostics-grid">
      <div class="diagnostics-item">
        <span class="diagnostics-label">Platform:</span>
        <span class="diagnostics-value">{navigator.platform}</span>
      </div>
      <div class="diagnostics-item diagnostics-item--full-width">
        <span class="diagnostics-label">User Agent:</span>
        <span class="diagnostics-value diagnostics-value--path">{navigator.userAgent}</span>
      </div>
    </div>
  </div>
</Dialog>
