// fiberpath_gui/src/components/StreamTab/ConnectionSection.tsx
/**
 * ConnectionSection - Serial port selection and connection management
 *
 * Features:
 * - Port selector dropdown
 * - Refresh ports button
 * - Baud rate selector
 * - Connect/Disconnect button
 * - Connection status indicator
 */

import { useEffect } from "react";
import { RefreshCw, Circle } from "lucide-react";
import { useStreamStore } from "../../stores/streamStore";
import { useConnectionActions } from "../../hooks/stream/useConnectionActions";
import "./ConnectionSection.css";

export function ConnectionSection() {
  const {
    status,
    selectedPort,
    baudRate,
    availablePorts,
    setSelectedPort,
    setBaudRate,
  } = useStreamStore();
  const { refreshing, refreshPorts, handleConnect, handleDisconnect } =
    useConnectionActions();

  // Load ports on mount
  useEffect(() => {
    void refreshPorts();
  }, []);

  const getStatusTone = () => {
    switch (status) {
      case "connected":
        return "connected";
      case "connecting":
        return "connecting";
      case "paused":
        return "paused";
      case "disconnected":
      default:
        return "disconnected";
    }
  };

  const getStatusText = () => {
    switch (status) {
      case "connected":
        return `Connected to ${selectedPort}`;
      case "connecting":
        return "Connecting...";
      case "paused":
        return "Paused";
      case "disconnected":
      default:
        return "Disconnected";
    }
  };

  return (
    <section className="connection-section panel panel--compact">
      <h3 className="panel-title">Connection</h3>

      <div className="connection-row">
        <label htmlFor="port-select" className="connection-label">
          Port
        </label>
        <div className="port-select-group">
          <select
            id="port-select"
            value={selectedPort || ""}
            onChange={(e) => setSelectedPort(e.target.value)}
            disabled={status !== "disconnected"}
            className="param-form__select connection-select"
          >
            {availablePorts.length === 0 ? (
              <option value="">No ports found</option>
            ) : (
              availablePorts.map((port) => (
                <option key={port.port} value={port.port}>
                  {port.port} - {port.description}
                </option>
              ))
            )}
          </select>
          <button
            onClick={refreshPorts}
            disabled={refreshing || status !== "disconnected"}
            className="btn btn--secondary btn--icon-only"
            title="Refresh ports"
            aria-label="Refresh serial ports"
          >
            <RefreshCw
              size={16}
              className={refreshing ? "stream-icon-spin" : undefined}
            />
          </button>
        </div>
      </div>

      <div className="connection-row">
        <label htmlFor="baud-select" className="connection-label">
          Baud
        </label>
        <select
          id="baud-select"
          value={baudRate}
          onChange={(e) => setBaudRate(Number(e.target.value))}
          disabled={status !== "disconnected"}
          className="param-form__select connection-select"
        >
          <option value={115200}>115200</option>
          <option value={250000}>250000</option>
          <option value={500000}>500000</option>
        </select>
      </div>

      <div className={`connection-status connection-status--${getStatusTone()}`}>
        <Circle
          size={12}
          fill="currentColor"
          color="currentColor"
          className="connection-status__dot"
        />
        <span className="connection-status__text">{getStatusText()}</span>
      </div>

      {status === "disconnected" ? (
        <button
          onClick={handleConnect}
          disabled={!selectedPort || availablePorts.length === 0}
          className="btn btn--primary connection-action-button"
          title="Connect to the selected serial port"
        >
          Connect
        </button>
      ) : (
        <button
          onClick={handleDisconnect}
          disabled={status === "connecting"}
          className="btn btn--secondary connection-action-button"
          title="Disconnect from the current device"
        >
          Disconnect
        </button>
      )}
    </section>
  );
}

// fiberpath_gui/src/components/machine/ConnectionSection.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { machineSession as m } from "../../state/machine-session.svelte";
  import { BAUD_RATES } from "../../lib/constants";
  import InspectorSection from "../../ui/InspectorSection.svelte";

  onMount(() => void m.refreshPorts());

  const statusText = $derived(
    m.status === "connected"
      ? `Connected to ${m.selectedPort}`
      : m.status === "connecting"
        ? "Connecting…"
        : m.status === "paused"
          ? "Paused"
          : "Disconnected",
  );
</script>

<InspectorSection title="Connection">
  <div class="field">
    <label for="port-select">Port</label>
    <div class="row">
      <select id="port-select" bind:value={m.selectedPort} disabled={m.status !== "disconnected"}>
        {#if m.ports.length === 0}
          <option value={null}>No ports found</option>
        {:else}
          {#each m.ports as p (p.port)}<option value={p.port}>{p.port} — {p.description}</option>{/each}
        {/if}
      </select>
      <button
        class="icon-btn"
        title="Refresh serial ports"
        aria-label="Refresh serial ports"
        disabled={m.refreshing || m.status !== "disconnected"}
        onclick={() => m.refreshPorts()}>⟳</button
      >
    </div>
  </div>

  <div class="field">
    <label for="baud-select">Baud</label>
    <select id="baud-select" bind:value={m.baudRate} disabled={m.status !== "disconnected"}>
      {#each BAUD_RATES as b (b)}<option value={b}>{b}</option>{/each}
    </select>
  </div>

  <div class="status" data-tone={m.status}>
    <span class="status__dot" aria-hidden="true"></span>
    <span>{statusText}</span>
  </div>

  {#if m.status === "disconnected"}
    <button
      class="btn btn--primary btn--block"
      disabled={!m.selectedPort || m.ports.length === 0}
      onclick={() => m.connect()}>Connect</button
    >
  {:else}
    <button class="btn btn--secondary btn--block" disabled={m.status === "connecting"} onclick={() => m.disconnect()}>
      Disconnect
    </button>
  {/if}
</InspectorSection>

<style>
  .field {
    margin-bottom: var(--spacing-sm);
  }
  .field label {
    display: block;
    font-size: var(--font-size-xs);
    color: var(--color-text-muted);
    margin-bottom: 2px;
  }
  .row {
    display: flex;
    gap: var(--spacing-xs);
  }
  select {
    flex: 1;
    height: var(--input-height-sm);
    background: var(--color-bg-panel-alt);
    color: var(--color-text);
    border: 1px solid var(--color-border);
    border-radius: var(--border-radius-sm);
    font-size: var(--font-size-sm);
    padding: 0 var(--spacing-xs);
  }
  .status {
    display: flex;
    align-items: center;
    gap: var(--spacing-xs);
    font-size: var(--font-size-sm);
    margin: var(--spacing-sm) 0;
  }
  .status__dot {
    width: 8px;
    height: 8px;
    border-radius: var(--border-radius-round);
    background: var(--color-text-muted);
  }
  .status[data-tone="connected"] .status__dot {
    background: var(--status-success);
  }
  .status[data-tone="connecting"] .status__dot {
    background: var(--status-warning);
  }
  .status[data-tone="paused"] .status__dot {
    background: var(--status-caution);
  }
</style>
