// fiberpath_gui/src/components/machine/StreamLog.svelte
<script lang="ts">
  import { prefersReducedMotion } from "svelte/motion";
  import { machineSession as m } from "../../state/machine-session.svelte";
  import type { LogEntry } from "../../state/machine-session.svelte";
  import EmptyState from "../../ui/EmptyState.svelte";

  let endEl = $state<HTMLDivElement>();

  $effect(() => {
    // Re-run when entries are appended; scroll to the latest if auto-scroll is on.
    m.log.length;
    if (m.autoScroll) {
      endEl?.scrollIntoView({ behavior: prefersReducedMotion.current ? "auto" : "smooth" });
    }
  });

  const prefix = (t: LogEntry["type"]) =>
    t === "command" ? ">" : t === "response" ? "<" : t === "stream" ? "•" : t === "error" ? "!" : t === "progress" ? "→" : "●";
</script>

<div class="log">
  <header class="log__header">
    <h3 class="log__title">Output Log</h3>
    <div class="log__actions">
      <button
        class="icon-btn"
        class:icon-btn--active={m.autoScroll}
        title={m.autoScroll ? "Auto-scroll on (click to disable)" : "Auto-scroll off (click to enable)"}
        aria-label="Toggle auto-scroll"
        onclick={() => m.toggleAutoScroll()}>⤓</button
      >
      <button class="icon-btn" title="Clear log" disabled={m.log.length === 0} onclick={() => m.clearLog()}>🗑</button>
    </div>
  </header>
  <div class="log__body">
    {#if m.log.length === 0}
      <EmptyState title="No log entries yet" hint="Connect to a device to get started." />
    {:else}
      {#each m.log as e (e.id)}
        <div class="entry" data-type={e.type}>
          <span class="entry__prefix">{prefix(e.type)}</span><span class="entry__content">{e.content}</span>
        </div>
      {/each}
      <div bind:this={endEl}></div>
    {/if}
  </div>
</div>

<style>
  .log {
    display: flex;
    flex-direction: column;
    height: 100%;
    min-height: 0;
    border-left: 1px solid var(--color-border);
    background: var(--color-bg-panel);
  }
  .log__header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    height: 1.75rem;
    padding: 0 var(--spacing-md);
    background: var(--color-bg-panel-alt);
    border-bottom: 1px solid var(--color-border);
  }
  .log__title {
    margin: 0;
    font-size: var(--font-size-xs);
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: var(--color-text-muted);
  }
  .log__actions {
    display: flex;
    gap: var(--spacing-xs);
  }
  .log__body {
    flex: 1;
    min-height: 0;
    overflow-y: auto;
    padding: var(--spacing-sm);
    font-family: var(--font-family-mono);
    font-size: var(--font-size-xs);
    line-height: var(--line-height-normal);
  }
  .entry {
    display: flex;
    gap: var(--spacing-sm);
    color: var(--color-text);
  }
  .entry__prefix {
    color: var(--color-text-muted);
  }
  .entry[data-type="command"] {
    color: var(--color-primary-soft);
  }
  .entry[data-type="response"] {
    color: var(--color-slate-400);
  }
  .entry[data-type="error"] {
    color: var(--status-error-fg);
  }
  .entry[data-type="stream"] {
    color: var(--color-text-muted);
  }
</style>

// fiberpath_gui/src/components/StreamTab/StreamLog.tsx
/**
 * StreamLog - Scrollable output log with syntax highlighting
 *
 * Features:
 * - Display log entries with type-based styling
 * - Auto-scroll to bottom
 * - Clear log button
 * - Virtualized rendering for performance (future enhancement)
 */

import { useEffect, useRef } from "react";
import { Trash2, ScrollText } from "lucide-react";
import { useStreamStore } from "../../stores/streamStore";
import type { LogEntry } from "../../stores/streamStore";
import "./StreamLog.css";

export function StreamLog() {
  const { logEntries, clearLog, autoScroll, toggleAutoScroll } =
    useStreamStore();
  const logEndRef = useRef<HTMLDivElement>(null);
  const scrollContainerRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to bottom when new entries are added (if enabled)
  useEffect(() => {
    if (autoScroll && logEndRef.current) {
      logEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [logEntries, autoScroll]);

  const getEntryClassName = (entry: LogEntry) => {
    return `log-entry log-entry--${entry.type}`;
  };

  const getEntryPrefix = (entry: LogEntry) => {
    switch (entry.type) {
      case "command":
        return ">";
      case "response":
        return "<";
      case "stream":
        return "•";
      case "error":
        return "!";
      case "progress":
        return "→";
      case "info":
      default:
        return "●";
    }
  };

  return (
    <div className="stream-log panel-container">
      <div className="stream-log__header panel-header">
        <h3 className="panel-title">Output Log</h3>
        <div className="stream-log__controls">
          <button
            onClick={toggleAutoScroll}
            className={`btn btn--ghost btn--icon-only stream-log__auto-scroll ${
              autoScroll ? "stream-log__auto-scroll--active" : ""
            }`}
            title={
              autoScroll
                ? "Auto-scroll enabled (click to disable)"
                : "Auto-scroll disabled (click to enable)"
            }
          >
            <ScrollText size={16} />
          </button>
          <button
            onClick={clearLog}
            className="btn btn--ghost btn--icon-only stream-log__clear"
            title="Clear log"
            disabled={logEntries.length === 0}
          >
            <Trash2 size={16} />
          </button>
        </div>
      </div>

      <div className="stream-log__content panel-body text-mono" ref={scrollContainerRef}>
        {logEntries.length === 0 ? (
          <div className="log-empty">
            No log entries yet. Connect to a device to get started.
          </div>
        ) : (
          <>
            {logEntries.map((entry) => (
              <div key={entry.id} className={getEntryClassName(entry)}>
                <span className="log-entry__prefix">
                  {getEntryPrefix(entry)}
                </span>
                <span className="log-entry__content">{entry.content}</span>
              </div>
            ))}
            <div ref={logEndRef} />
          </>
        )}
      </div>
    </div>
  );
}
